language: node_js
node_js:
  - "6"
scripts:
  - npm test
services: 
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "select * from pg_settings where name = 'port'" -U postgres